/* Generated by MyraPad at 11.03.2022 13:28:04 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class GameSaveWindow: Window
	{
		private void BuildUI()
		{
			saveBtn = new ImageTextButton();
			saveBtn.Text = "Sauvegarder";
			saveBtn.Padding = new Thickness(3);
			saveBtn.Id = "saveBtn";

			saveNameInput = new TextBox();
			saveNameInput.HintText = "Nom de la sauvegarde";
			saveNameInput.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			saveNameInput.Id = "saveNameInput";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Top = 1;
			horizontalStackPanel1.Margin = new Thickness(6, 0, 4, 8);
			horizontalStackPanel1.Widgets.Add(saveBtn);
			horizontalStackPanel1.Widgets.Add(saveNameInput);

			container = new VerticalStackPanel();
			container.Spacing = 5;
			container.Padding = new Thickness(5);
			container.Id = "container";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = container;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(scrollViewer1);

			
			Title = "Sauvegarder Sous ...";
			Left = 314;
			Top = 97;
			MinWidth = 400;
			MaxWidth = 700;
			MinHeight = 250;
			MaxHeight = 300;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
		public ImageTextButton saveBtn;
		public TextBox saveNameInput;
		public VerticalStackPanel container;
	}
}
