/* Generated by MyraPad at 03.02.2022 14:59:06 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class GameSaveWindow: Window
	{
		private void BuildUI()
		{
			var imageTextButton1 = new ImageTextButton();
			imageTextButton1.Text = "Sauvegarder";
			imageTextButton1.Padding = new Thickness(3);

			var textBox1 = new TextBox();
			textBox1.HintText = "Nom de la sauvegarde";
			textBox1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			horizontalStackPanel1.Top = 1;
			horizontalStackPanel1.Margin = new Thickness(6, 0, 4, 8);
			horizontalStackPanel1.Widgets.Add(imageTextButton1);
			horizontalStackPanel1.Widgets.Add(textBox1);

			var imageTextButton2 = new ImageTextButton();
			imageTextButton2.Text = "maSuperColonie - 2022-01-19 12:05:05";
			imageTextButton2.Toggleable = true;
			imageTextButton2.Padding = new Thickness(5);
			imageTextButton2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton3 = new ImageTextButton();
			imageTextButton3.Text = "maSuperColonie - 2022-01-18 16:00:34";
			imageTextButton3.Toggleable = true;
			imageTextButton3.Padding = new Thickness(5);
			imageTextButton3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton4 = new ImageTextButton();
			imageTextButton4.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton4.Toggleable = true;
			imageTextButton4.Padding = new Thickness(5);
			imageTextButton4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton5 = new ImageTextButton();
			imageTextButton5.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton5.Toggleable = true;
			imageTextButton5.Padding = new Thickness(5);
			imageTextButton5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton6 = new ImageTextButton();
			imageTextButton6.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton6.Toggleable = true;
			imageTextButton6.Padding = new Thickness(5);
			imageTextButton6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton7 = new ImageTextButton();
			imageTextButton7.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton7.Toggleable = true;
			imageTextButton7.Padding = new Thickness(5);
			imageTextButton7.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton8 = new ImageTextButton();
			imageTextButton8.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton8.Toggleable = true;
			imageTextButton8.Padding = new Thickness(5);
			imageTextButton8.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton9 = new ImageTextButton();
			imageTextButton9.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton9.Toggleable = true;
			imageTextButton9.Padding = new Thickness(5);
			imageTextButton9.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton10 = new ImageTextButton();
			imageTextButton10.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton10.Toggleable = true;
			imageTextButton10.Padding = new Thickness(5);
			imageTextButton10.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton11 = new ImageTextButton();
			imageTextButton11.Text = "maSuperColonie - 2021-01-15 17:31:12";
			imageTextButton11.Toggleable = true;
			imageTextButton11.Padding = new Thickness(5);
			imageTextButton11.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 5;
			verticalStackPanel1.Padding = new Thickness(5);
			verticalStackPanel1.Widgets.Add(imageTextButton2);
			verticalStackPanel1.Widgets.Add(imageTextButton3);
			verticalStackPanel1.Widgets.Add(imageTextButton4);
			verticalStackPanel1.Widgets.Add(imageTextButton5);
			verticalStackPanel1.Widgets.Add(imageTextButton6);
			verticalStackPanel1.Widgets.Add(imageTextButton7);
			verticalStackPanel1.Widgets.Add(imageTextButton8);
			verticalStackPanel1.Widgets.Add(imageTextButton9);
			verticalStackPanel1.Widgets.Add(imageTextButton10);
			verticalStackPanel1.Widgets.Add(imageTextButton11);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = verticalStackPanel1;

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel2.Widgets.Add(scrollViewer1);

			
			Title = "Sauvegarder Sous ...";
			Left = 314;
			Top = 36;
			MinWidth = 400;
			MaxWidth = 700;
			MinHeight = 250;
			MaxHeight = 300;
			Id = "Win";
			Content = verticalStackPanel2;
		}

		
	}
}
