/* Generated by MyraPad at 11.03.2022 13:15:37 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class MainMenuScreenGameLoadWindow: Window
	{
		private void BuildUI()
		{
			container = new VerticalStackPanel();
			container.Spacing = 5;
			container.Padding = new Thickness(5);
			container.Id = "container";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = container;

			
			Title = "Charger une partie";
			Left = 314;
			Top = 97;
			MinWidth = 400;
			MaxWidth = 700;
			MinHeight = 250;
			MaxHeight = 300;
			Id = "Win";
			Content = scrollViewer1;
		}

		
		public VerticalStackPanel container;
	}
}
