/* Generated by MyraPad at 03.02.2022 14:26:10 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class MainMenuScreenGameConfigWindow: Window
	{
		private void BuildUI()
		{
			var imageTextButton1 = new ImageTextButton();
			imageTextButton1.Text = "Reprendre";
			imageTextButton1.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton1.Padding = new Thickness(4);
			imageTextButton1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var label1 = new Label();
			label1.Height = 8;

			var imageTextButton2 = new ImageTextButton();
			imageTextButton2.Text = "Sauvegarder";
			imageTextButton2.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton2.Padding = new Thickness(4);
			imageTextButton2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton3 = new ImageTextButton();
			imageTextButton3.Text = "Sauvegarder Sous ...";
			imageTextButton3.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton3.Padding = new Thickness(4);
			imageTextButton3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton4 = new ImageTextButton();
			imageTextButton4.Text = "Charger ...";
			imageTextButton4.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton4.Padding = new Thickness(4);
			imageTextButton4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var label2 = new Label();
			label2.Height = 8;

			var imageTextButton5 = new ImageTextButton();
			imageTextButton5.Text = "Sauvegarder et Quitter";
			imageTextButton5.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton5.Padding = new Thickness(4);
			imageTextButton5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var imageTextButton6 = new ImageTextButton();
			imageTextButton6.Text = "Quitter sans Sauvegarder";
			imageTextButton6.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			imageTextButton6.Padding = new Thickness(4);
			imageTextButton6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.Padding = new Thickness(10);
			verticalStackPanel1.Widgets.Add(imageTextButton1);
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(imageTextButton2);
			verticalStackPanel1.Widgets.Add(imageTextButton3);
			verticalStackPanel1.Widgets.Add(imageTextButton4);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(imageTextButton5);
			verticalStackPanel1.Widgets.Add(imageTextButton6);

			
			Title = "Sauvegarder";
			Left = 389;
			Top = 30;
			MinWidth = 250;
			MaxWidth = 700;
			MinHeight = 0;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
	}
}
