/* Generated by MyraPad at 04.02.2022 14:23:09 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class MainMenuScreenGameConfigWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "boolean";

			var checkBox1 = new CheckBox();
			checkBox1.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			checkBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			checkBox1.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "text";
			label2.GridRow = 1;

			var textBox1 = new TextBox();
			textBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			textBox1.MinWidth = 200;
			textBox1.GridColumn = 1;
			textBox1.GridRow = 1;

			var label3 = new Label();
			label3.Text = "number";
			label3.GridRow = 2;

			var spinButton1 = new SpinButton();
			spinButton1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			spinButton1.MinWidth = 200;
			spinButton1.GridColumn = 1;
			spinButton1.GridRow = 2;

			var label4 = new Label();
			label4.Text = "combobox";
			label4.GridRow = 3;

			var listItem1 = new ListItem();
			listItem1.Text = "option1";

			var listItem2 = new ListItem();
			listItem2.Text = "option2";

			var comboBox1 = new ComboBox();
			comboBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			comboBox1.GridColumn = 1;
			comboBox1.GridRow = 3;
			comboBox1.Items.Add(listItem1);
			comboBox1.Items.Add(listItem2);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 10;
			grid1.RowSpacing = 10;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Padding = new Thickness(5);
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(checkBox1);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(textBox1);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(spinButton1);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(comboBox1);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = grid1;

			var tabItem1 = new TabItem();
			tabItem1.Text = "test213";
			tabItem1.Content = scrollViewer1;

			var tabItem2 = new TabItem();
			tabItem2.Text = "test213";
			tabItem2.Content = null;

			var tabControl1 = new TabControl();
			tabControl1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			tabControl1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			tabControl1.MinHeight = 200;
			tabControl1.MaxHeight = 300;
			tabControl1.Items.Add(tabItem1);
			tabControl1.Items.Add(tabItem2);

			ConfirmGameParamsButton = new ImageTextButton();
			ConfirmGameParamsButton.Text = "OK";
			ConfirmGameParamsButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			ConfirmGameParamsButton.Id = "ConfirmGameParamsButton";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.Widgets.Add(tabControl1);
			verticalStackPanel1.Widgets.Add(ConfirmGameParamsButton);

			
			Title = "Configuration de la partie";
			Left = 314;
			Top = 92;
			MinWidth = 400;
			MaxWidth = 700;
			MinHeight = 250;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
		public ImageTextButton ConfirmGameParamsButton;
	}
}
