/* Generated by MyraPad at 20.01.2022 13:17:55 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class MainMenuScreenMainMenuWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "ANTPIRE";
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();

			NewGameBtn = new ImageTextButton();
			NewGameBtn.Text = "Nouvelle Partie";
			NewGameBtn.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			NewGameBtn.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			NewGameBtn.Padding = new Thickness(20, 10);
			NewGameBtn.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			NewGameBtn.Id = "NewGameBtn";

			LoadGameBtn = new ImageTextButton();
			LoadGameBtn.Text = "Charger Partie";
			LoadGameBtn.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			LoadGameBtn.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			LoadGameBtn.Padding = new Thickness(20, 10);
			LoadGameBtn.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			LoadGameBtn.Id = "LoadGameBtn";

			QuitBtn = new ImageTextButton();
			QuitBtn.Text = "Quitter";
			QuitBtn.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			QuitBtn.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			QuitBtn.Padding = new Thickness(20, 10);
			QuitBtn.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			QuitBtn.Id = "QuitBtn";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 15;
			verticalStackPanel1.Padding = new Thickness(15);
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(NewGameBtn);
			verticalStackPanel1.Widgets.Add(LoadGameBtn);
			verticalStackPanel1.Widgets.Add(QuitBtn);

			
			Title = "";
			Left = 420;
			Top = 42;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
		public ImageTextButton NewGameBtn;
		public ImageTextButton LoadGameBtn;
		public ImageTextButton QuitBtn;
	}
}
