/* Generated by MyraPad at 15.03.2022 09:58:17 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class MainMenuScreenGameConfigWindow: Window
	{
		private void BuildUI()
		{
			propertyGrid = new PropertyGrid();
			propertyGrid.Id = "propertyGrid";

			ConfirmGameParamsButton = new ImageTextButton();
			ConfirmGameParamsButton.Text = "OK";
			ConfirmGameParamsButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			ConfirmGameParamsButton.Id = "ConfirmGameParamsButton";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.Widgets.Add(propertyGrid);
			verticalStackPanel1.Widgets.Add(ConfirmGameParamsButton);

			
			Title = "Configuration de la partie";
			Left = 314;
			Top = 97;
			MinWidth = 400;
			MaxWidth = 700;
			MinHeight = 250;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
		public PropertyGrid propertyGrid;
		public ImageTextButton ConfirmGameParamsButton;
	}
}
