/* Generated by MyraPad at 20.01.2022 13:18:10 */
namespace Antpire.Screens.Windows
{
	public partial class MainMenuScreenGameConfigWindow
	{
		public MainMenuScreenGameConfigWindow()
		{
			BuildUI();
		}
	}
}