/* Generated by MyraPad at 03.02.2022 14:16:23 */

using Myra.Graphics2D.UI;

namespace Antpire.Screens.Windows;

public partial class PauseWindow {
	private Desktop desktop;

	public PauseWindow(Desktop desktop) {
		BuildUI();

		this.desktop = desktop;

		Continue.Click += (s, a) => {
			Visible = false;
		};

		Load.Click += (s, a) => {
			var test = new MainMenuScreenGameLoadWindow();
			desktop.Widgets.Add(test);
		};


		SaveAs.Click += (s, a) => {
			var test = new GameSaveWindow();
			desktop.Widgets.Add(test);
		};
	}
}