/* Generated by MyraPad at 03.02.2022 15:23:42 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Antpire.Screens.Windows
{
	partial class PauseWindow: Window
	{
		private void BuildUI()
		{
			Continue = new ImageTextButton();
			Continue.Text = "Reprendre";
			Continue.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Continue.Padding = new Thickness(4);
			Continue.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			Continue.Id = "Continue";

			var label1 = new Label();
			label1.Height = 8;

			Save = new ImageTextButton();
			Save.Text = "Sauvegarder";
			Save.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Save.Padding = new Thickness(4);
			Save.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			Save.Id = "Save";

			SaveAs = new ImageTextButton();
			SaveAs.Text = "Sauvegarder Sous ...";
			SaveAs.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			SaveAs.Padding = new Thickness(4);
			SaveAs.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			SaveAs.Id = "SaveAs";

			Load = new ImageTextButton();
			Load.Text = "Charger ...";
			Load.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Load.Padding = new Thickness(4);
			Load.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			Load.Id = "Load";

			var label2 = new Label();
			label2.Height = 8;

			SaveAndQuit = new ImageTextButton();
			SaveAndQuit.Text = "Sauvegarder et Quitter";
			SaveAndQuit.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			SaveAndQuit.Padding = new Thickness(4);
			SaveAndQuit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			SaveAndQuit.Id = "SaveAndQuit";

			Quit = new ImageTextButton();
			Quit.Text = "Quitter sans Sauvegarder";
			Quit.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Quit.Padding = new Thickness(4);
			Quit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			Quit.Id = "Quit";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.Padding = new Thickness(10);
			verticalStackPanel1.Widgets.Add(Continue);
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(Save);
			verticalStackPanel1.Widgets.Add(SaveAs);
			verticalStackPanel1.Widgets.Add(Load);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(SaveAndQuit);
			verticalStackPanel1.Widgets.Add(Quit);

			
			Title = "Sauvegarder";
			Left = 389;
			Top = 34;
			MinWidth = 250;
			MaxWidth = 700;
			MinHeight = 0;
			Id = "Win";
			Content = verticalStackPanel1;
		}

		
		public ImageTextButton Continue;
		public ImageTextButton Save;
		public ImageTextButton SaveAs;
		public ImageTextButton Load;
		public ImageTextButton SaveAndQuit;
		public ImageTextButton Quit;
	}
}
